---
apiVersion: v1
kind: Service
metadata:
  name: txterv8
spec:
  type: LoadBalancer
  selector:
    app: txterv8
  ports:
    - port: 80
      name: http
      targetPort: 8888
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: txterv8
spec:
  selector:
    matchLabels:
      app: txterv8
  template:
    metadata:
      labels:
        app: txterv8
    spec:
      containers:
        - name: txterv8
          image: docker.io/kenttwilio/prime:txterv8
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
